"""
Cookie Manager for authenticated downloads (yt-dlp and gallery-dl).

Handles parsing raw cookie strings from browser DevTools and converting
them to Netscape cookie file format for yt-dlp and gallery-dl consumption.
"""
import os
import sqlite3
import hashlib
import logging
from datetime import datetime, timedelta, timezone
from typing import Optional
from pathlib import Path

logger = logging.getLogger(__name__)

# Domain mappings for supported platforms
PLATFORM_DOMAINS = {
    "instagram": ".instagram.com",
    "tiktok": ".tiktok.com",
    "twitter": ".twitter.com",
    "facebook": ".facebook.com",
    "reddit": ".reddit.com",
    "youtube": ".youtube.com",
    "flickr": ".flickr.com",
    "tumblr": ".tumblr.com",
    "imgur": ".imgur.com",
    "pixiv": ".pixiv.net",
    "deviantart": ".deviantart.com",
    "pinterest": ".pinterest.com",
    "bluesky": ".bsky.app",
    "danbooru": ".donmai.us",
}


# In-memory cache: { platform: filepath }
# Invalidated by db_upsert_cookie() and db_delete_cookie()
_cookie_file_cache: dict[tuple[str, str], str] = {}  # (user id, platform) -> cookie file

# Staleness threshold (days) -- hardcoded, not user-configurable
COOKIE_STALE_DAYS = 7


def parse_cookie_string(cookie_str: str) -> list[tuple[str, str]]:
    """
    Parse a raw cookie header string into name-value pairs.

    Args:
        cookie_str: Cookie string like "sessionid=abc123; csrftoken=xyz789"

    Returns:
        List of (name, value) tuples
    """
    cookies = []
    if not cookie_str:
        return cookies

    # Split by semicolon and parse each cookie
    for part in cookie_str.split(";"):
        part = part.strip()
        if not part or "=" not in part:
            continue
        # Split only on first = (value may contain =)
        name, value = part.split("=", 1)
        name = name.strip()
        value = value.strip()
        if name:
            cookies.append((name, value))

    return cookies


def to_netscape_format(platform: str, cookies: list[tuple[str, str]]) -> str:
    """
    Convert cookies to Netscape cookie file format.

    Format per line:
    domain  domain_initial_dot  path  secure  expiry  name  value

    Args:
        platform: Platform name (e.g., "instagram")
        cookies: List of (name, value) tuples

    Returns:
        Netscape format cookie file content
    """
    domain = PLATFORM_DOMAINS.get(platform, f".{platform}.com")

    lines = ["# Netscape HTTP Cookie File"]
    lines.append("# Generated by immich-drop")
    lines.append("")

    for name, value in cookies:
        # domain, domain_initial_dot, path, secure, expiry, name, value
        # Using TRUE for domain_initial_dot (leading dot), FALSE for secure,
        # and 0 for expiry (session cookie / no expiry)
        line = f"{domain}\tTRUE\t/\tFALSE\t0\t{name}\t{value}"
        lines.append(line)

    return "\n".join(lines) + "\n"


def get_cookie_dir() -> str:
    """Get the cookie directory, creating it if needed."""
    cookie_dir = os.path.join(os.getenv("DATA_DIR", "").strip() or "/data", "cookies")

    os.makedirs(cookie_dir, exist_ok=True)
    return cookie_dir


def _safe_platform(platform: str) -> str:
    """Reject platform names that aren't in the allowlist or that contain
    path separators / dots. Raises ValueError for callers to surface as 400.
    """
    p = (platform or "").strip().lower()
    if not p or p not in PLATFORM_DOMAINS:
        raise ValueError(f"unsupported platform: {platform!r}")
    return p


def _user_dirname(user_id: str) -> str:
    """Directory name for one user's cookie files ("_" = no user, e.g. the iOS Shortcut)."""
    return hashlib.sha256(user_id.encode("utf-8")).hexdigest()[:16] if user_id else "_"


def _platform_filepath(platform: str, user_id: str = "") -> str:
    """Build a cookie filepath that is provably inside the cookie directory."""
    p = _safe_platform(platform)
    base = Path(get_cookie_dir()).resolve()
    user_dir = base / _user_dirname(user_id)
    user_dir.mkdir(exist_ok=True)
    target = (user_dir / f"{p}.txt").resolve()
    try:
        target.relative_to(base)
    except ValueError:
        raise ValueError(f"path escape: {platform!r}")
    return str(target)


def write_cookie_file(platform: str, cookie_string: str, user_id: str = "") -> str:
    """
    Write a Netscape format cookie file for the given platform.

    Args:
        platform: Platform name (e.g., "instagram")
        cookie_string: Raw cookie header string

    Returns:
        Path to the written cookie file
    """
    p = _safe_platform(platform)
    filepath = _platform_filepath(p, user_id)
    cookies = parse_cookie_string(cookie_string)
    content = to_netscape_format(p, cookies)

    with open(filepath, "w") as f:
        f.write(content)

    # Set restrictive permissions (owner read/write only)
    try:
        os.chmod(filepath, 0o600)
    except OSError:
        pass  # May fail on some systems

    return filepath


def delete_cookie_file(platform: str, user_id: str = "") -> bool:
    """
    Delete the cookie file for a platform.

    Args:
        platform: Platform name

    Returns:
        True if deleted, False if not found
    """
    try:
        filepath = _platform_filepath(platform, user_id)
    except ValueError:
        return False

    if os.path.exists(filepath):
        os.remove(filepath)
        return True
    return False


def is_cookie_stale(updated_at: str, stale_days: int = COOKIE_STALE_DAYS) -> bool:
    """Check if a cookie's updated_at timestamp is older than stale_days."""
    if not updated_at:
        return True
    try:
        updated = datetime.fromisoformat(updated_at)
        if updated.tzinfo is None:
            updated = updated.replace(tzinfo=timezone.utc)
        threshold = datetime.now(timezone.utc) - timedelta(days=stale_days)
        return updated < threshold
    except (ValueError, TypeError):
        return True


def get_cookie_file_for_platform(platform: str, state_db: str, user_id: str = "") -> Optional[str]:
    """
    Look up a user's cookies for a platform from the database and return the cookie file path.

    Uses an in-memory cache to avoid rewriting the Netscape file on every call.
    Logs a warning when cookies are stale.

    Args:
        platform: Platform name (e.g., "instagram")
        state_db: Path to the SQLite database
        user_id: Immich user id the cookies belong to ("" = no user)

    Returns:
        Path to cookie file, or None if no cookies for this platform
    """
    if not platform:
        return None

    platform = platform.lower()

    # Check cache first to avoid DB query on every download
    cache_key = (user_id, platform)
    cached_path = _cookie_file_cache.get(cache_key)
    if cached_path and os.path.exists(cached_path):
        logger.debug("Using cached cookie file for %s", platform)
        return cached_path

    # Cache miss -- query DB
    try:
        conn = sqlite3.connect(state_db)
        cur = conn.cursor()
        cur.execute(
            "SELECT cookie_string, updated_at FROM platform_cookies WHERE user_id = ? AND platform = ?",
            (user_id, platform)
        )
        row = cur.fetchone()
        conn.close()

        if not row or not row[0]:
            return None

        cookie_string, updated_at = row

        # Warn on stale cookies (only on cache miss, not every call)
        if is_cookie_stale(updated_at):
            logger.warning(
                "Cookies for %s may be expired (last updated: %s). "
                "Re-export from your browser if downloads fail.",
                platform, updated_at,
            )

        filepath = write_cookie_file(platform, cookie_string, user_id)
        _cookie_file_cache[cache_key] = filepath
        logger.debug("Wrote fresh cookie file for %s at %s", platform, filepath)
        return filepath

    except Exception as e:
        logger.warning("Failed to get cookies for platform %s: %s", platform, e)
        return None


# Database operations for cookie CRUD

def db_list_cookies(state_db: str, user_id: str = "") -> list[dict]:
    """List a user's platform cookies."""
    try:
        conn = sqlite3.connect(state_db)
        conn.row_factory = sqlite3.Row
        cur = conn.cursor()
        cur.execute(
            "SELECT platform, cookie_string, created_at, updated_at "
            "FROM platform_cookies WHERE user_id = ? ORDER BY platform",
            (user_id,),
        )
        rows = cur.fetchall()
        conn.close()
        return [dict(row) for row in rows]
    except Exception as e:
        logger.warning("Failed to list cookies: %s", e)
        return []


def db_upsert_cookie(state_db: str, platform: str, cookie_string: str, user_id: str = "") -> bool:
    """Create or update a user's platform cookie."""
    platform = platform.lower()
    try:
        conn = sqlite3.connect(state_db)
        cur = conn.cursor()
        cur.execute(
            """
            INSERT INTO platform_cookies (user_id, platform, cookie_string, updated_at)
            VALUES (?, ?, ?, CURRENT_TIMESTAMP)
            ON CONFLICT(user_id, platform) DO UPDATE SET
                cookie_string = excluded.cookie_string,
                updated_at = CURRENT_TIMESTAMP
            """,
            (user_id, platform, cookie_string)
        )
        conn.commit()
        conn.close()

        # Also write the cookie file immediately
        write_cookie_file(platform, cookie_string, user_id)
        _cookie_file_cache.pop((user_id, platform), None)
        logger.info("Saved cookies for platform: %s", platform)
        return True
    except Exception as e:
        logger.exception("Failed to save cookie for %s: %s", platform, e)
        return False


def db_delete_cookie(state_db: str, platform: str, user_id: str = "") -> bool:
    """Delete a user's platform cookie."""
    platform = platform.lower()
    try:
        conn = sqlite3.connect(state_db)
        cur = conn.cursor()
        cur.execute(
            "DELETE FROM platform_cookies WHERE user_id = ? AND platform = ?",
            (user_id, platform)
        )
        deleted = cur.rowcount > 0
        conn.commit()
        conn.close()

        # Also delete the cookie file
        delete_cookie_file(platform, user_id)
        _cookie_file_cache.pop((user_id, platform), None)

        if deleted:
            logger.info("Deleted cookies for platform: %s", platform)
        return deleted
    except Exception as e:
        logger.exception("Failed to delete cookie for %s: %s", platform, e)
        return False
